### ISSUE TITLE
Detects whole image as one blob?

### ISSUE THREAD

**Issue by tiktuk** [keenerd/quickblob#3]
The last line of the output is always a blob encompassing the entire image. Is that on purpose?

Example from `lorem.png` sample image:

    2004.16,1994.31,14589776,255,0,0,3999,3999

**Comment by keenerd** [comment]
Yes.  It is a contiguous region of pixels of a matching color.

**Comment by tiktuk** [comment]
Ah, right, I see. So'll just filter it out afterwards.
